services:
  support-bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
    # networks:
    #   - remnawave-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

# networks:
#   remnawave-network:
#     name: remnawave-network
#     external: true